name: Build, Test, and Deploy
on:
  - push

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Create envfile
        run: |
          echo "TF_VAR_git_repo=${{ github.repositoryUrl }}" > sink.env
      # - name: Stash envfile
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: sink-env
      #     path: sink.env

  call-sink:
    needs:
      - init
    uses: corey-cole/experimental-action-workflows/.github/workflows/env-sink-actions.yml@main
    with:
      var-file: sink-env
